services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"
    networks:
      - erasmus-network
    depends_on:
      - backend

  backend:
    build: ./backend
    environment:
      DATABASE_URL: mysql+pymysql://user:password@db/main_db
    networks:
      - erasmus-network
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: main_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - erasmus-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

networks:
  erasmus-network:
    driver: bridge

volumes:
  mysql_data: